package com.offlinevault.ui.components

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ContentCopy
import androidx.compose.material.icons.filled.Refresh
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.ModalBottomSheet
import androidx.compose.material3.Slider
import androidx.compose.material3.Switch
import androidx.compose.material3.Text
import androidx.compose.material3.rememberModalBottomSheetState
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.offlinevault.security.GeneratorOptions
import com.offlinevault.security.PasswordGenerator
import com.offlinevault.security.PasswordStrengthChecker
import com.offlinevault.utils.ClipboardHelper

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun PasswordGeneratorSheet(
    onDismiss: () -> Unit,
    onUse: (String) -> Unit
) {
    val sheetState = rememberModalBottomSheetState(skipPartiallyExpanded = true)
    val context = LocalContext.current

    var options by remember { mutableStateOf(GeneratorOptions()) }
    var generated by remember { mutableStateOf(PasswordGenerator.generate(options)) }

    fun regenerate(newOptions: GeneratorOptions = options) {
        var safe = newOptions
        if (!safe.useUpper && !safe.useLower && !safe.useDigits && !safe.useSymbols) {
            safe = safe.copy(useLower = true)
        }
        options = safe
        generated = PasswordGenerator.generate(safe)
    }

    val strength = PasswordStrengthChecker.evaluate(generated)

    ModalBottomSheet(
        onDismissRequest = onDismiss,
        sheetState = sheetState,
        containerColor = MaterialTheme.colorScheme.surface
    ) {
        Column(Modifier.padding(horizontal = 20.dp).padding(bottom = 28.dp)) {
            Text("密码生成器", style = MaterialTheme.typography.titleLarge, fontWeight = FontWeight.SemiBold)
            Spacer(Modifier.height(16.dp))

            SectionCard {
                Column {
                    Row(
                        Modifier.fillMaxWidth(),
                        verticalAlignment = Alignment.CenterVertically,
                        horizontalArrangement = Arrangement.SpaceBetween
                    ) {
                        Text(
                            generated,
                            style = MaterialTheme.typography.titleMedium,
                            fontFamily = FontFamily.Monospace,
                            modifier = Modifier.weight(1f)
                        )
                        IconButton(onClick = { regenerate() }) {
                            Icon(Icons.Filled.Refresh, contentDescription = "重新生成", tint = MaterialTheme.colorScheme.primary)
                        }
                        IconButton(onClick = {
                            ClipboardHelper.copySensitive(context, "生成的密码", generated, 10)
                        }) {
                            Icon(Icons.Filled.ContentCopy, contentDescription = "复制", tint = MaterialTheme.colorScheme.primary)
                        }
                    }
                    Spacer(Modifier.height(10.dp))
                    StrengthMeter(score = strength.score, level = strength.level)
                }
            }

            Spacer(Modifier.height(16.dp))

            Text("长度：${options.length}", style = MaterialTheme.typography.labelLarge)
            Slider(
                value = options.length.toFloat(),
                onValueChange = { regenerate(options.copy(length = it.toInt())) },
                valueRange = PasswordGenerator.MIN_LENGTH.toFloat()..PasswordGenerator.MAX_LENGTH.toFloat()
            )

            ToggleRow("大写字母（A-Z）", options.useUpper) { regenerate(options.copy(useUpper = it)) }
            ToggleRow("小写字母（a-z）", options.useLower) { regenerate(options.copy(useLower = it)) }
            ToggleRow("数字（0-9）", options.useDigits) { regenerate(options.copy(useDigits = it)) }
            ToggleRow("符号（!@#）", options.useSymbols) { regenerate(options.copy(useSymbols = it)) }

            Spacer(Modifier.height(16.dp))
            PrimaryButton(
                text = "使用此密码",
                onClick = { onUse(generated) },
                modifier = Modifier.fillMaxWidth()
            )
        }
    }
}

@Composable
private fun ToggleRow(label: String, checked: Boolean, onChange: (Boolean) -> Unit) {
    Row(
        Modifier.fillMaxWidth().height(48.dp),
        verticalAlignment = Alignment.CenterVertically,
        horizontalArrangement = Arrangement.SpaceBetween
    ) {
        Text(label, style = MaterialTheme.typography.bodyLarge)
        Switch(checked = checked, onCheckedChange = onChange)
    }
}
